### ISSUE TITLE
Cannot load a backup file on production app

### ISSUE THREAD

**Issue by kitakaze-kan** [OWND-Project/OWND-Wallet-iOS#10]
I found the backup file from icould is not working and "select_invalid_backup_file" error showed up on the OWND Wallet.

IPhone15 
iOS: 17.4.1
OWND Wallet ver: v0.1.5

![IMG_1035](https://github.com/OWND-Project/OWND-Wallet-iOS/assets/46702100/b0a9416b-faf2-4157-9365-0b550dfb7105)

**Comment by kitakaze-kan** [comment]
FYI, here is the content of my backup file ( unzipped ).

```
{"idTokenSharingHistories":[],"credentialSharingHistories":[],"seed":"<12 secret phrase>"}
```

**Comment by moratori** [comment]
@kitakaze-kan Thank you for reporting the backup-related issue!
The direct cause of this problem was insufficient permissions when manipulating files.

```
Code=257 "ファイル“owned_wallet_2024-06-05.zip”を表示するためのアクセス権がないため、開けませんでした。"
```

I have created a [pull request](https://github.com/OWND-Project/OWND-Wallet-iOS/pull/14) to address the above issue and several other backup-related issues.
